# Generated by Django 2.0 on 2018-07-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180416_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='author',
            field=models.CharField(default='の管理者', max_length=255, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='author_mail',
            field=models.EmailField(default='@gmail.com', max_length=255, verbose_name='管理者アドレス'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='color',
            field=models.CharField(choices=[('primary', '青色'), ('secondary', '灰色'), ('success', '緑色'), ('info', '水色'), ('warning', '黄色'), ('danger', '赤'), ('dark', '黒')], default='info', max_length=30, verbose_name='サイトテーマ色'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='description',
            field=models.TextField(default='の説明', max_length=255, verbose_name='サイトの説明'),
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='header_text',
            field=models.TextField(default='プログラミング学習記録＆雑記\n[filter url]https://<split>*********[end]', max_length=255, verbose_name='ヘッダーのテキスト'),
        ),
    ]
