# Generated by Django 2.0.7 on 2018-07-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180723_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.AlterField(
            model_name='sitedetail',
            name='header_text',
            field=models.TextField(default='', max_length=255, verbose_name='ヘッダーのテキスト'),
        ),
    ]
